pipeline:
  name: "DistributedSkiResortSystem"
  description: "Simplified CI/CD pipeline for demo"
  stages:
    - build
    - test

# Build stage - compile and install
maven-compile:
  stage: build
  image: maven:3.8.6-openjdk-11
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
    "/Users/di/.m2/repository": "/root/.m2/repository"
  script: "mvn clean install -DskipTests -T 1C"

# Test stage - run tests
maven-test:
  stage: test
  image: maven:3.8.6-openjdk-11
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
    "/Users/di/.m2/repository": "/root/.m2/repository"
  needs: [maven-compile]
  script: "mvn test"