pipeline:
  name: artifacts-success-pipeline
  description: Simplified pipeline demonstrating 3 artifact pattern types with real files

stages:
  - build
  - test

# Job 1: Test single file and directory patterns
# Uses real project files (README.md, pom.xml) and real Maven compilation
compile:
  - stage: build
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Compiling consumer module only (fast)..."
    - mvn clean compile -DskipTests -pl consumer -am
    - echo "Compilation completed"
  - artifacts:
    # Pattern 1: Single file by name (real project files)
    - README.md
    - pom.xml

# Job 2: Test directory and star patterns
# Uses real Maven test reports and JAR files
test:
  - stage: test
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Running tests and packaging consumer module only..."
    - mvn test -pl consumer
    - mvn package -DskipTests -pl consumer
    - echo "Test and package completed"
  - artifacts:
    # Pattern 2: Directory (real test reports)
    - consumer/target/surefire-reports/
    # Pattern 3a: Single star (real JAR files)
    - consumer/target/*.jar
    # Pattern 3b: Double star (any depth - finds all XML files)
    - "**/*.xml"

