pipeline:
  name: artifacts-success-pipeline
  description: Simplified pipeline demonstrating 3 artifact pattern types

stages:
  - build
  - test

# Job 1: Test single file and directory patterns
test-basic:
  - stage: build
  - image: alpine:latest
  - script:
    - echo "Creating test files and directories..."
    # Create single files
    - echo "Main readme" > README.md
    - echo "Config file" > config.xml
    # Create a directory structure
    - mkdir -p build/output
    - echo "Build artifact 1" > build/output/app.jar
    - echo "Build artifact 2" > build/output/lib.jar
    - echo "Build log" > build/build.log
    - echo "Test files created"
  - artifacts:
    # Pattern 1: Single file by name
    - README.md
    - config.xml
    # Pattern 2: Directory (recursive)
    - build/

# Job 2: Test star patterns (* and **)
test-patterns:
  - stage: test
  - image: alpine:latest
  - script:
    - echo "Creating files for pattern matching..."
    # Create files for single star pattern
    - mkdir -p app/target
    - mkdir -p lib/target
    - echo "app jar" > app/target/app.jar
    - echo "lib jar" > lib/target/lib.jar
    - echo "app log" > app/target/test.log
    # Create nested structure for double star pattern
    - mkdir -p deep/nested/dir/docs
    - echo "doc1" > deep/doc.txt
    - echo "doc2" > deep/nested/doc.txt
    - echo "doc3" > deep/nested/dir/docs/doc.txt
    - echo "Pattern test files created"
  - artifacts:
    # Pattern 3a: Single star (one level)
    - "*/target/*.jar"  # Matches app/target/app.jar, lib/target/lib.jar
    # Pattern 3b: Double star (any depth)
    - "**/doc.txt"  # Matches all doc.txt at any depth

