pipeline:
  name: artifacts-success-pipeline
  description: Simplified pipeline demonstrating 3 artifact pattern types with real files

stages:
  - build
  - test

# Job 1: Test single file and directory patterns
# Uses real project files (README.md, pom.xml) and real Maven compilation
compile:
  - stage: build
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Compiling server-spring module only (fast)..."
    - mvn clean compile -DskipTests -pl server-spring -am
    - echo "Compilation completed"
  - artifacts:
    # Pattern 1: Single file by name (real project files)
    - README.md
    - pom.xml

# Job 2: Test directory and star patterns
# Uses real Maven test reports and JAR files
test:
  - stage: test
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Packaging server-spring module only..."
    - mvn package -DskipTests -pl server-spring -am
    - echo "Package completed"
  - artifacts:
    # Pattern 2: Directory (real build output)
    - server-spring/target/classes/
    # Pattern 3a: Single star (real JAR files at one level)
    - server-spring/target/*.jar
    # Pattern 3b: Double star (any depth - finds all nested Java files)
    - "server-spring/**/neu/**/*.java"

