pipeline:
  name: artifacts-success-pipeline
  description: Example pipeline demonstrating successful artifact upload with real Maven build

stages:
  - build
  - test
  - package
  - deploy

# Compile job - demonstrates single file pattern
compile:
  - stage: build
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Compiling Maven project..."
    - mvn clean compile -DskipTests
    - echo "Compilation completed successfully"
  - artifacts:
    # Example 1: A file, by providing a file name
    # Note: CLI auto-injects git clone directly to /workspace
    - README.md
    - pom.xml

# Test job - demonstrates directory and simple star patterns
test:
  - stage: test
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Running Maven tests..."
    - mvn test
    - echo "Tests completed successfully"
  - artifacts:
    # Example 2: A directory (recursively uploads all contents)
    # Note: Using consumer module as example since it has clear structure
    - consumer/target/surefire-reports/
    # Example 3a: Star for any match
    - consumer/target/*.jar  # All JAR files in target
    - "*.xml"  # All XML files (pom.xml, etc.)

# Package job - demonstrates double star pattern (any depth)
package:
  - stage: package
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Packaging Maven project..."
    - mvn package -DskipTests
    - echo "Packaging completed successfully"
  - artifacts:
    # Example 3b: Double star for any depth
    - "**/*.jar"  # All JAR files at any depth
    - "**/*.war"  # All WAR files at any depth
    # Example 3a.iii: Single star in directory path (one level only)
    - "*/target/*.jar"  # JAR files in target dirs one level down

# Deploy job - demonstrates directory patterns with wildcards
deploy:
  - stage: deploy
  - image: maven:3.8.6-openjdk-8
  - script:
    - echo "Preparing deployment artifacts..."
    - mkdir -p dist/libs
    - mkdir -p dist/docs
    - mkdir -p consumer/target/generated-docs
    - find . -name "*.jar" -path "*/target/*" -exec cp {} dist/libs/ \;
    - find . -name "*.war" -path "*/target/*" -exec cp {} dist/libs/ \;
    - echo "Sample doc" > dist/docs/README.txt
    - echo "Generated" > consumer/target/generated-docs/api.html
    - echo "Deployment artifacts prepared"
  - artifacts:
    # Example 2: Directory with trailing /
    - dist/  # Uploads entire dist directory recursively
    # Example 3a.iii: Single star directory pattern (one level away)
    - "dist/*/README.txt"  # Matches dist/docs/README.txt (one level)
    # Example 3b.i: Double star directory pattern (any depth)
    - "**/target/generated-docs/"  # All generated-docs dirs at any depth

