pipeline:
  name: "DistributedSkiResortSystem"
  description: "Simplified CI/CD pipeline for demo"
  stages:
    - build
    - test

# Build stage - compile and install
maven-compile:
  stage: build
  image: openjdk:21-jdk-slim
  workingDirectory: "/workspace"
  volumeMounts:
    "/home/di/Distributed-Ski-Resort-System": "/workspace"
    "/home/di/.m2/repository": "/root/.m2/repository"
  script: "apt-get update && apt-get install -y maven && mvn clean install -DskipTests -T 1C"

# Test stage - run tests
maven-test:
  stage: test
  image: openjdk:21-jdk-slim
  workingDirectory: "/workspace"
  volumeMounts:
    "/home/di/Distributed-Ski-Resort-System": "/workspace"
    "/home/di/.m2/repository": "/root/.m2/repository"
  needs: [maven-compile]
  script: "apt-get update && apt-get install -y maven && mvn test"