pipeline:
  name: "DistributedSkiResortSystem"
  description: "Simplified CI/CD pipeline for demo"
  stages:
    - build
    - test

# Build stage - compile and install
maven-compile:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
  script: "mvn -B clean install -DskipTests -T 1C"

# (removed) Build stage - style check to keep only 1 job in build stage

# Test stage - run tests
maven-test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
  script: "mvn -B test"

# Test stage - integration tests (example)
integration-test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
  needs: [maven-test]
  script: "mvn -B -DskipUnitTests verify"