pipeline:
  name: "failure-pipeline"
  description: "Example of a failed CI/CD pipeline execution with detailed logs"

stages:
  - build
  - test
  - deploy

# Build stage - this job will fail during compilation with a real error
failing-compile:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: |
    # Find a Java file and introduce a real syntax error
    JAVA_FILE=$(find . -name "*.java" -type f -path "*/src/main/java/*" | head -1)
    if [ -n "$JAVA_FILE" ]; then
      # Add an invalid line at the beginning to break compilation
      sed -i '1i public class InvalidSyntaxError {' "$JAVA_FILE"
    else
      # Create a broken Java file if none found
      mkdir -p src/main/java/com/example
      cat > src/main/java/com/example/BrokenClass.java << 'EOF'
    public class BrokenClass {
        public void brokenMethod() {
            System.out.println("This will fail");
        // Missing closing braces
    EOF
    fi
    # This will fail with real Maven compilation errors
    mvn -B clean compile -DskipTests

# Build stage - this job should not run if failing-compile fails
build-job:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  needs:
    - failing-compile
  script: "mvn -B clean compile -DskipTests"

# Test stage - should not run if build stage fails (runs after build stage completes)
test-job:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B test"

# Deploy stage - should not run if build stage fails (runs after test stage completes)
deploy-job:
  stage: deploy
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B deploy -DskipTests"
