# Simple CI/CD Pipeline with First Job Failing
# This pipeline demonstrates failed job execution for database testing

pipeline:
  name: "SimpleFailPipeline"
  description: "Simple pipeline where first job fails to demonstrate failed job storage"
  stages:
    - build
    - test

# First job - this will fail intentionally
maven-compile:
  stage: build
  image: openjdk:21-jdk-slim
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
  script: "mvn clean compile && exit 1"  # This will fail with exit code 1

# Second job - depends on first job, will be skipped due to failure
maven-test:
  stage: test
  image: openjdk:21-jdk-slim
  workingDirectory: "/workspace"
  volumeMounts:
    "/Users/di/Downloads/DistributedSkiResortSystem": "/workspace"
  needs: [maven-compile]
  script: "mvn test"