pipeline:
  name: "Invalid cross-stage needs demo"
  description: "This file intentionally violates: needs must reference jobs in the same stage"
  stages:
    - build
    - test

# Build stage
build-job:
  stage: build
  image: alpine:3.19
  script: |
    echo "Building..."

# Test stage with invalid cross-stage needs (references build-stage job)
test-job:
  stage: test
  image: alpine:3.19
  needs: [build-job]  # INVALID: needs must reference jobs within the same stage
  script: |
    echo "Testing..."


