pipeline:
  name: distributed-ski-resort-pipeline-broken
  description: Broken demo pipeline for Distributed Ski Resort System - Demonstrates failure scenarios for classroom demonstration

stages:
  - build
  - test

# Single build job with intentional errors
build-and-test:
  - stage: build
  - image: maven:3.8-eclipse-temurin-8
  - script:
    - echo "=== BROKEN BUILD AND TEST STAGE ==="
    - echo "Checking Java version..."
    - java -version
    - echo "Current working directory:"
    - pwd
    - echo "Installing dependencies first..."
    - mvn clean install -pl swagger-client -am
    - echo "Building main modules with WRONG module name..."
    - mvn clean compile -pl server-spring-wrong,client-part1
    - echo "Running quick tests..."
    - mvn test -pl server-spring
    - echo "Minimal pipeline completed successfully"

# Quick validation job with intentional error
quick-check:
  - stage: test
  - image: maven:3.8-eclipse-temurin-8
  - script:
    - echo "=== QUICK VALIDATION CHECK ==="
    - echo "Validating project structure..."
    - mvn validate
    - echo "Checking for compilation errors with WRONG command..."
    - mvn compile-wrong -q
    - echo "Quick validation completed successfully"
