pipeline:
  name: "success-pipeline"
  description: "Example of a successful CI/CD pipeline execution"

stages:
  - build
  - test
  - deploy

# Build stage - compile and install
maven-compile:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B clean install -DskipTests -T 1C"

# Build stage - code style check
style-check:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B checkstyle:check || (echo 'Checkstyle plugin not configured, skipping' && true)"

# Test stage - unit tests (runs after build stage completes)
maven-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B test"

# Deploy stage - package deployment (runs after test stage completes)
deploy:
  stage: deploy
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B deploy -DskipTests || (echo 'Deploy skipped (may require repository configuration)' && true)"
