pipeline:
  name: success-pipeline
  description: Example pipeline demonstrating successful execution with real Maven build

stages:
  - build
  - test

# Compile job - compiles all Maven modules successfully
maven-compile:
  - stage: build
  - image: maven:3.8.6-openjdk-8
  - workingDirectory: "/workspace"
  - script:
    - echo "Compiling Maven project..."
    - mvn clean compile -DskipTests
    - echo "Compilation completed successfully"

# Test job - runs unit tests successfully
# Note: This job will automatically run after the build stage completes
maven-test:
  - stage: test
  - image: maven:3.8.6-openjdk-8
  - workingDirectory: "/workspace"
  - script:
    - echo "Running Maven tests..."
    - mvn test
    - echo "Tests completed successfully"

