pipeline:
  name: "DistributedSkiResortSystem"
  description: "CI/CD pipeline for demo"

stages:
  - build
  - test
  - deploy

# Build stage - compile and install
maven-compile:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B clean install -DskipTests -T 1C"

# Build stage - code style check (no dependencies, can run in parallel with maven-compile)
style-check:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B checkstyle:check"

# Build stage - dependency check (no dependencies, can run in parallel with maven-compile)
dependency-check:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B dependency:analyze"

# Build stage - spotbugs check (no dependencies, can run in parallel with other build jobs)
spotbugs-check:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B spotbugs:check"

# Build stage - PMD check (no dependencies, can run in parallel with other build jobs)
pmd-check:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B pmd:check"

# Build stage - findbugs check (no dependencies, can run in parallel with other build jobs)
findbugs-check:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B findbugs:check"

# Test stage - unit tests (no dependencies, can run in parallel with other test jobs)
maven-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B test"

# Test stage - integration tests (no dependencies, can run in parallel with maven-test)
integration-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B -DskipUnitTests verify"

# Test stage - code coverage (no dependencies, can run in parallel with other test jobs)
coverage-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B test jacoco:report"

# Test stage - security scan (no dependencies, can run in parallel with other test jobs)
security-scan:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B org.owasp:dependency-check-maven:check"

# Test stage - mutation testing (no dependencies, can run in parallel with other test jobs)
mutation-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B org.pitest:pitest-maven:mutationCoverage"

# Test stage - performance test (no dependencies, can run in parallel with other test jobs)
performance-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B jmeter:jmeter"

# Deploy stage - package deployment (no dependencies)
deploy:
  stage: deploy
  image: maven:3.9-eclipse-temurin-17
  workingDirectory: "/workspace"
  script: "mvn -B deploy -DskipTests"
