pipeline:
  name: "DistributedSkiResortSystem"
  description: "CI/CD pipeline for demo"
  stages:
    - build
    - test

maven-compile:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - rm -rf /workspace/source 2>/dev/null || true
    - git clone https://github.com/Di-123-Di/Distributed-Ski-Resort-System.git /workspace/source
    - cd /workspace/source
    - mvn -B clean install -DskipTests -T 1C
  needs: []

maven-test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - rm -rf /workspace/source 2>/dev/null || true
    - git clone https://github.com/Di-123-Di/Distributed-Ski-Resort-System.git /workspace/source
    - cd /workspace/source
    - mvn -B test
  needs: []

